# Generated by Django 5.2.14 on 2026-06-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('free', 'free'), ('sold', 'sold'), ('rental', 'rental')], max_length=250, null=True),
        ),
    ]
