# Generated by Django 5.2.14 on 2026-06-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ningas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ninja',
            new_name='Ninga',
        ),
    ]
