# Generated by Django 5.2.14 on 2026-06-02 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ningas_app', '0002_rename_ninja_ninga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninga',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ningas', to='dojo_ningas_app.dojo'),
        ),
    ]
