# Generated by Django 5.2.14 on 2026-06-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ningas_app', '0003_alter_ninga_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
